// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-94EQ41Ic8kEpNVBqsSbkJa_YBrsE7M0',
    appId: '1:698030242237:web:4146289974ab5e6887bad4',
    messagingSenderId: '698030242237',
    projectId: 'quadro-204be',
    authDomain: 'quadro-204be.firebaseapp.com',
    storageBucket: 'quadro-204be.firebasestorage.app',
    measurementId: 'G-HDB06MS76C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy4vQeOdM4OZlqi6Cyj6oil43a6pi-Iqg',
    appId: '1:698030242237:android:ad1865a658ad5ad187bad4',
    messagingSenderId: '698030242237',
    projectId: 'quadro-204be',
    storageBucket: 'quadro-204be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx3UUF8rAdimrWOUI0qqL9vNUBBzGeMNY',
    appId: '1:698030242237:ios:81936f1226fa2aa587bad4',
    messagingSenderId: '698030242237',
    projectId: 'quadro-204be',
    storageBucket: 'quadro-204be.firebasestorage.app',
    iosBundleId: 'com.example.quadroPlatform',
  );
}
